name: My First Workflow

on: 
  workflow_dispatch:

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout Repo
          uses: actions/checkout@v4
          
        - name: Welcome message
          run: echo "Hello GitHub Actions"

        - name: List files
          run: ls

        - name: Read file
          run: cat README.md




