name: Generate ASCII Art

on: push

jobs:
    ascii_job:
        runs-on: ubuntu-latest
        steps:
        - name: Chcekout Repo
          uses: actions/checkout@v4
        
        - name: List files
          run: ls

        - name: Executing Shell Script
          run: |
            chmod +x ascii-script.sh
            ./ascii-script.sh