name: Test GitHub variables

on: 
  push:

jobs:
  dev_job:
    if: contains(github.ref, 'dev')
    runs-on: ubuntu-latest
    environment:
      name: dev
    steps:
        - name: Dev Build job
          run: echo "${{ vars.ENVIRONMENT }} Build Job Running"
        
        - name: Dev Deploy job
          run: echo "${{ vars.ENVIRONMENT }} Deploy Job Running"
    
  prod_job:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment:
      name: prod
    steps:
        - name: Prod Build job
          run: echo "${{ vars.ENVIRONMENT }} Build Job Running"
        
        - name: Prod Deploy job
          run: echo "${{ vars.ENVIRONMENT }} Build Job Running"