name: My First Workflow

on: 
  push:
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      output1: ${{ steps.step1.outputs.test }}
      output2: ${{ steps.step2.outputs.test }}
    steps:
      - id: step1
        run: echo "test=hello" >> "$GITHUB_OUTPUT"
      - id: step2
        run: echo "test=world" >> "$GITHUB_OUTPUT"

  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - env:
          OUTPUT1: ${{needs.job1.outputs.output1}}
          OUTPUT2: ${{needs.job1.outputs.output2}}
        run: echo "$OUTPUT1 $OUTPUT2"

  job3:
    runs-on: ubuntu-latest
    steps:
      - name: Create a Step Output variable
        run: |
          echo "STEP_OUTPUT=step_output_123" >> "$GITHUB_ENV"

      - name: Get a Step Output variable
        run: |
          echo ${{ env.STEP_OUTPUT}}