name: Matrix Configuration

on: 
  workflow_dispatch:

jobs:
    deploy:
        strategy:
          fail-fast: false
          max-parallel: 2 
          matrix:
              os: [ubuntu-latest, windows-latest]
              images: [hello-world, alpine]
              exclude:
                - image: alpine
                  os: windows-latest
              include:
                - image: amd64/alpine
                  os: ubuntu-20.04
        runs-on: ${{ matrix.os }}
        steps:      
        - name: Echo Docker details
          run: docker info

        - name: Run Image on ${{ matrix.os }}
          run: docker run ${{ matrix.images }}