name: Reusable workflow

on:
  workflow_call:
    inputs:
      input1:
        required: true
        type: string
      input2:
        description: Input of the caller workflow
        default: "Hello World"
        required: false
        type: string
    secrets:
      secret1: 
        required: true
    outputs:
      output1:
        value: ${{ jobs.reuse-job.outputs.output_job}}

jobs:
  reuse-job:
    runs-on: ubuntu-latest
    environment:
      name: ${{inputs.input1}}
    outputs:
      output_job: ${{ steps.step1.outputs.output_job }}
    steps:
      - name: Input Message
        id: step1
        run: |
          echo "${{inputs.input1}} ${{inputs.input2}}"
          "output_job=${{inputs.input1}} ${{inputs.input2}}" >> "$GITHUB_OUTPUT"
          