name: Docker Workflow

on: push

env:
    CONTAINER_REGISTRY: docker.io
    DOCKER_UERNAME: test1
    IMAGE_NAME: github-actions-ngnix

jobs:
    docker_build:
        runs-on: ubuntu-latest
        steps:      
        - name: Docker Build
          run: echo docker build -t ${{env.CONTAINER_REGISTRY}}/$DOCKER_UERNAME/$IMAGE_NAME:latest

        - name: Docker Login
          run: echi docker login --username=$DOCKER_USERNAME --password=${{secrets.DOCKER_PASSWORD}}

        - name: Docker Publish
          run: echo docker push $CONTAINER_REGISTRY/$DOCKER_UERNAME/$IMAGE_NAME:latest

    docker_deploy:
      needs: docker_build
      runs-on: ubuntu-latest
      steps:
        - name: Docker Run
          run: echo docker run -d -p 8080:80 $CONTAINER_REGISTRY/$DOCKER_UERNAME/$IMAGE_NAME:latest