name: Docker Workflow

on: 
  workflow_dispatch:

env:
    CONTAINER_REGISTRY: docker.io
    IMAGE_NAME: github-actions-ngnix

jobs:
    docker_build:
        runs-on: ubuntu-latest
        steps:      
        - name: Docker Build
          run: echo docker build -t ${{env.CONTAINER_REGISTRY}}/${{vars.DOCKER_UERNAME}}/$IMAGE_NAME:latest

        - name: Docker Login
          run: echo docker login --username=$DOCKER_USERNAME --password=${{secrets.DOCKER_PASSWORD}}

        - name: Docker Publish
          run: echo docker push $CONTAINER_REGISTRY/${{vars.DOCKER_UERNAME}}/$IMAGE_NAME:latest

    docker_deploy:
      if: github.ref == 'refs/heads/main'
      needs: docker_build
      concurrency:
        group: production-deployment
        cancel-in-progress: false
      runs-on: ubuntu-latest
      steps:
        - name: Docker Run
          timeout-minutes: 1
          run: |
            echo docker run -d -p 8080:80 $CONTAINER_REGISTRY/${{vars.DOCKER_UERNAME}}/$IMAGE_NAME:latest
            sleep 600s